version: "3.9"

# The different services that make up our "network" of containers
services:
  # MariaDB Database
  mariadb:
    image: mariadb:10
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: g8
      MARIADB_USER: codeql
      MARIADB_PASSWORD: codeql
    # Remove comment if want to expose MariaDB service to host
    ports:
      - 3306:3306
  # Express frontend
  frontend:
    # The location of dockerfile to build this service
    build: ./frontend
    environment:
      NODE_ENV: production
    # Ports to map our port 80, to the port 5000 on the container
    ports:
      - 80:5000
  # Express backend
  backend:
    # The location of dockerfile to build this service
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        PRECOMPILE_QUERIES: "false" # TO REDUCE CREATION TIME
        # PRECOMPILE_QUERIES: "true"
    environment:
      CODEQL_HOME: /usr/local/codeql-home
      DB_NAME: g8
      DB_USER: codeql
      DB_PASSWORD: codeql
    # Ports to map our port 8080, to the port 8080 on the container
    ports:
      - 8080:8080
    # Tell docker this container depends on the neo service & mariadb so they can communicate
    depends_on:
      - neo
      - mariadb
  # Neo4j Database
  neo:
    # The image to use
    image: neo4j:4.2.7
    # map the ports so we can check the db server is up
    ports:
      - 7474:7474
      - 7687:7687
    # mounting a named volume to the container to track db data
    volumes:
      - neo4j_data:/data/
    environment:
      - NEO4J_AUTH=neo4j/s3cr3t # configure the instance with custom username/password
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G

# volumes to be generated, these are saved somewhere for repeated use by docker
volumes:
  neo4j_data:
  mariadb_data:
