import React from "react";
import { Row, Col, Card, Container } from "@themesberg/react-bootstrap";

const DocsFAQ = () => (
  <Container className="px-0">
    <Row>
      <Col xs={12} className="p-3">
        <Card>
          <Card.Body>
            <article>
              <h1 className="h2" id="license">
                FAQ
              </h1>
              <p className="fs-5 fw-light">
                We know you might have questions regarding the tool, here is a
                list of the most common questions asked and our answers to them.
              </p>

              <h2 className="fs-5 mt-2" id="">
                How do I upload my source code for scanning?
              </h2>
              <p>
                You can head over to the Dashboard tab, and choose whether you
                want to upload a file, folder, or even a Github Repository link.
                You can then browse your local files or drag and drop the file
                into the space provided. After upload is complete, you can close
                the upload window.
              </p>

              <h2 className="fs-5 mt-2" id="">
                How do I start analyzing my code?
              </h2>
              <p>
                After uploading your code, wait for a few seconds for the
                project to show up under Existing Projects List. Once it shows
                up, you can click analyze and analzye will turn into
                "Processing". From there, you have to wait for the "Processing"
                status to turn into "Load Project". After clicking "Load
                Project", wait a few seconds and an alert box would show up
                saying that "Project has been successfully loaded". Click "OK".
                You can now click the Overview tab to see how the code flows as
                we have implemented Neo4J into G8 for clear visuals. You can
                also go into CodeQL Alerts to view the alerts generated by
                CodeQL.
              </p>

              <h2 className="fs-5 mt-2" id="">
                How does Sarif Viewer work?
              </h2>
              <p>
                Sarif Viewer is an additional feature in our tool G8. You can
                use it to view Sarif files in a more read-able format.
              </p>

              <h2 className="fs-5 mt-2" id="">
                How to view code analysis?
              </h2>
              <p>
                You can now click the Overview tab to see how the code flows as
                we have implemented Neo4J into G8 for clear visuals. You can
                also go into CodeQL Alerts to view the alerts generated by
                CodeQL. Last but not least, you can go into Sarif Viewer to view
                the sarif file.
              </p>

              <h2 className="fs-5 mt-2" id="">
                What happens to the code after I have analyzed them?
              </h2>

              <p>
                We have made it convenient for you such that you get to decide
                whether your code can be deleted or whether you still need to
                refer to it on G8.
              </p>

              <h2 className="fs-5 mt-2" id="">
                Is there a page which can help me better understand the
                complicated terms used in G8.
              </h2>
              <p>
                Yes there is a Glossary page under the Documentation tab in the
                sidebar which you can refer to for terms which you are unsure
                of.
              </p>

              <h2 className="fs-5 mt-2" id="">
                Can I use G8 on my mobile phone or tablet device?
              </h2>
              <p>
                It is not recommended as our tool G8 is developed for
                computer-use only.
              </p>

              <h2 className="fs-5 mt-2" id="">
                How many files can I upload at a time?
              </h2>
              <p>
                You can upload a maximum number of a 100 files. However, if you
                compress 101 files or more into a zip folder, they can be
                uploaded as well.
              </p>

              <h2 className="fs-5 mt-2" id="">
                Can I use G8 on any Operating System?
              </h2>
              <p>
                You can only use Docker on Windows, Mac and Linux Operating
                Systems. Hence, G8 can only be used on the ones which have been
                listed.
              </p>

              <h2 className="fs-5 mt-2" id="">
                Approximately how long would it take for my project to be
                analyzed?
              </h2>
              <p>
                As the CodeQL library is huge, the amount of time taken to
                analyze the project you have uploaded would depend on the
                processing power of the workstation you are working on.
              </p>

              <h2 className="fs-5 mt-2" id="">
                Why is the page which I opened not showing anything?
              </h2>
              <p>
                It may take some time so please be patient. You can also refresh
                the page as well and give it a few seconds for it to load.
              </p>

              <h2 className="fs-5 mt-2" id="">
                How do I delete the code I have uploaded and analyzed?
              </h2>
              <p>TBC</p>
            </article>
          </Card.Body>
        </Card>
      </Col>
    </Row>
  </Container>
);

export default DocsFAQ;
