export const Routes = {
  // pages
  Presentation: { path: "/" },
  Dashboard: { path: "/dashboard" },
  Overview: { path: "/overview" },
  CodeQLAlerts: { path: "/codeql-alerts" },
  PDFViewer: { path: "/pdfviewer" },
  SarifViewer: { path: "/sarifviewer" },
  Settings: { path: "/settings" },
  BootstrapTables: { path: "/tables/bootstrap-tables" },
  Billing: { path: "/examples/billing" },
  Invoice: { path: "/examples/invoice" },
  Signin: { path: "/examples/sign-in" },
  Signup: { path: "/examples/sign-up" },
  ForgotPassword: { path: "/examples/forgot-password" },
  ResetPassword: { path: "/examples/reset-password" },
  Lock: { path: "/examples/lock" },
  NotFound: { path: "/404" },
  ServerError: { path: "/500" },

  // docs
  DocsAbout: { path: "/documentation/about" },
  DocsExploring: { path: "/documentation/exploring-g8" },
  DocsQuickStart: { path: "/documentation/quick-start" },
  DocsFAQ: { path: "/documentation/faq" },
  DocsGlossary: { path: "/documentation/glossary" },
  DocsBuild: { path: "/documentation/build-tools" },
  DocsChangelog: { path: "/documentation/changelog" },

  // components
  Accordions: { path: "/components/accordions" },
  Alerts: { path: "/components/alerts" },
  Badges: { path: "/components/badges" },
  Widgets: { path: "/widgets" },
  Breadcrumbs: { path: "/components/breadcrumbs" },
  Buttons: { path: "/components/buttons" },
  Forms: { path: "/components/forms" },
  Modals: { path: "/components/modals" },
  Navs: { path: "/components/navs" },
  Navbars: { path: "/components/navbars" },
  Pagination: { path: "/components/pagination" },
  Popovers: { path: "/components/popovers" },
  Progress: { path: "/components/progress" },
  Tables: { path: "/components/tables" },
  Tabs: { path: "/components/tabs" },
  Tooltips: { path: "/components/tooltips" },
  Toasts: { path: "/components/toasts" },
  WidgetsComponent: { path: "/components/widgets" },
};
